


const replaceStr = [
    {
    "subActivityId":"64006df7d27e8d1bf829613a",
    "activityList":`Rolling a work mat,Unrolling work mat,
    Sitting on a sitting mat,Getting up from a sitting mat,
    Sitting on a work mat,Getting up from a work mat,Sitting on a chair,Getting up from a chair
    `										
},
{    
   "subActivityId":"64006e15d27e8d1bf829613e",
    "activityList":`Chowki,
    Chair,
    Bucket,
    Rolled mat,
    Rolled oil cloth,
    Small glass,
    Medium glass,
    Large glass,
    Lota,
    Napkin,
    Duster
    `											     
},
{    
    "subActivityId":"64006e29d27e8d1bf8296142",
     "activityList":`Chowki,
     Chair,
     Bucket,
     Rolled mat,
     Rolled oil Cloth,
     Small glass,
     Medium glass,
     Small jug,
     Large Jug,
     Lota,
     Napkin,
     Duster
     `											     
 },
 {    
    "subActivityId":"64006e4dd27e8d1bf8296146",
     "activityList":`Chowki,
     Chair,
     Bucket,
     Rolled mat,
     Rolled oil Cloth,
     Tray,
     Napkin,
     Duster,
     Sharp Object,
     Pointed Object,
     Broom,
     Dust pan and brush
     `											     
 },
 {    
    "subActivityId":"64006ebed27e8d1bf829614a",
     "activityList":`Fold Napkin (medials),
     Unfold Napkin ( medials),
     Fold Napkin (diagonals),
     Unfold Napkin (diagonals),
     Fold duster,
     Unfold duster,
     Roll an oil cloth,
     Unroll an oil cloth
     `											     
 },
  {    
    "subActivityId":"64006eddd27e8d1bf829614e",
     "activityList":`Sponge,
Dropper,
Funnel,
Spoon,
Grains (1:1),
Grains (1:3) equal,
Grains (1:3) unequal,
Liquids (1:1),
Liquids (1:3) equal,
Liquids (1:3) unequal `											     
 },
 {    
    "subActivityId":"64006efad27e8d1bf8296152",
     "activityList":`Watering a plant,
Care of plant,
Using dustpan and brush,
Sweeping,
Mopping with cloth,
Mopping with stick,
Cleaning mirror,
Washing chowki,
Washing clothes,
Dust a chowki,
Polish brass,
Shoe Polish,
Flower arrangment,
Stringing flowers,
Rangoli making,
Paper cutting,
Pattern cutting,
Weaving frame,
Needle a thread,
Sewing,
Sewing button
     `											     
 }, 
 {    
    "subActivityId":"64006f14d27e8d1bf8296156",
     "activityList":`To Greet,
Talk in society,
To Walk,
To Sneeze,
To Cough,
To Yawn,
Observe  person @ work,
Respond to signal,
Approach an adult,
Observe presentation,
Offer glass of water,
Offer sharp Object,
Offer pointed Object `											     
 },
  {    
    "subActivityId":"64006f33d27e8d1bf829615a",
     "activityList":`Washing  Hands,
Braiding-1,
Braiding-2,
Braiding-3,
Fasten press button,
Unfasten press button,
Fasten hooks,
Unfasten hooks,
Fasten Coat button,
Unfasten coat button,
Fasten Buckles,
Unfasten Buckles,
Tie base knot and bow,
Untie base knot and bow,
Tie 'V' pattern,
Untie 'V' pattern,
Tie 'X' pattern,
Untie 'X' pattern,
Tie linear pattern,
Untie linear pattern `											     
 },
 {    
    "subActivityId":"64006f7dd27e8d1bf8296168",
     "activityList":`Walking on line,
Walking on a line heel to toe,
Walking on a line with 1 object,
Walking on a line with 2 objects,
Silence activity,
Pealing/cutting fruit,
Pealing/ cutting vegetable,
Chapathi making,
Chandan paste making,
Drawing water from well`											     
 },
  {    
    "subActivityId":"64006faed27e8d1bf829616c",
     "activityList":`Parent presentation,
Reverse pairing Random,
Memory M1,
Memory M2,
Reverse pairing succession,
Grading with block,
Grading w/o block,
M2 in succession,
Possibilities (2,3,4),
Name Lessons,
Tall-short,
Thick-thin,
Small-big,
Tall and thin-Short and thick`											     
 },
  {    
    "subActivityId":"64006fc6d27e8d1bf8296170",
     "activityList":`Parent presentation,
Memory M2,
G1,
G2,
Group activity,
Name Lessons,
Big-small,
Comparitive names,
Superlative names`											     
 },
  {    
    "subActivityId":"64006fe9d27e8d1bf8296174",
     "activityList":`Parent presentation,
G1,
G2,
Name Lessons,
Thick-thin,
Comparitive names,
Superlative names`											     
 },
  {    
    "subActivityId":"640081b59efe8c0978572203",
     "activityList":`Parent presentation,
G1,
G2,
Family I (1,2,3),
Family II (1,2,3),
Family III (1,2,3),
Name Lessons,
Long-Short,
Comparitive names,
Superlative names`											     
 },
  {    
    "subActivityId":"640081f29efe8c0978572207",
     "activityList":`Presentation Box 1,
Activity Box 2,
Activity Box 2 M1,
Activity Box 2 M2,
Grading,
Combinatons with grading,
Exploratory activity, fetch an object,
Exploratory activity, fetch color tablet,
Exploratory,
Name Lessons,
Primary colours,
Secondary colours,
Tertiary Colours,
Comparitive names,
Superlative names`											     
 },
  {    
    "subActivityId":"6400820c9efe8c097857220b",
     "activityList":`Touch boards,
Fabric box 1,
Fabric Box 2,
Touch tablets pairing,
Touch tablet grading I,
Touch tablet grading II,
Exploratory,
Name Lessons,
Comparitive names,
Superlative names`											     
 },
  {    
    "subActivityId":"64018ab59efe8c0978572224",
     "activityList":`Parent presentation,
Memory M1,
Memory M2,
G1,
G2,
Grading I,
Grading II,
Exploratory,
Name Lessons,
Loud soft,
Comparitive names,
Superlative names`											     
 },
  {    
    "subActivityId":"64018b4d9efe8c097857222c",
     "activityList":`Parent presentation,
Reverse pairing Random,
Memory M1,
Memory M2,
Different shapes pairing,
Grading,
G1,
G2,
Finding cards for inset,
Finding inset for card,
Two or three set comb,
With cards only,
Grading,
Group activity,
Exploratory,
Name Lessons,
Basic shapes,
Triangles,
Quadrilaterals,
Polygons,
Curvilinear figures`											     
 },
  {    
    "subActivityId":"64018c4b9efe8c0978572233",
     "activityList":`Presentation pairing 2 solids,
All solids one face,
All solids diff faces,
Name Lesson,
Curvilinear solids,
Pyramids,
Prisms,
Naming the solid,
Finding the solid,
Isol Card find solid,
Isol solid Find the card,
Exploratory Act Clay`											     
 },
  {    
    "subActivityId":"64018c899efe8c0978572237",
     "activityList":`Presentation bag,
Bag 1,
Bag 2,
Bag 3,
Bag 4,
Bag 5,
Bag 6,
Mystery bag,
Coin Box ,`											     
 },
  {    
    "subActivityId":"64018d099efe8c097857223b",
     "activityList":`Parent Presentation,
Shrinking square,
Squares with same colour,
Making binomial,
Making trinomial`											     
 },
  {    
    "subActivityId":"64018db99efe8c097857223f",
     "activityList":`Parent Presentation,
Outside box,
Layers,
Sorting`											     
 },
  {    
    "subActivityId":"64018dce9efe8c0978572243",
     "activityList":`Parent Presentation,
Outside box,
Layers,
Sorting`											     
 },
  {    
    "subActivityId":"64018dea9efe8c0978572247",
     "activityList":`Rectangular Box,
Blue triangles,
Blue triangles sliding,
Blue triangles rotate,
Triangular Box,
Large Hexagonal Box,
Small hexagonal Box,
Supplementary Box`											     
 },
  {    
    "subActivityId":"64018dfd9efe8c097857224b",
     "activityList":`same shape 2 colour,
2 colour 2 shape,
 all`											     
 },
   {    
    "subActivityId":"64018e149efe8c097857224f",
     "activityList":`Parent present (red, yellow),
Building Tower,
Grading`											     
 },
   {    
    "subActivityId":"64018e3c9efe8c0978572253",
     "activityList":`Presentation,
Name Lessons,
Hot cold warm tepid,
Comparitive names,
Superlative names`											     
 },
   {    
    "subActivityId":"64018e519efe8c0978572257",
     "activityList":`Presentation,
One set sunlight,
Diff materials retaining capacity`											     
 },
   {    
    "subActivityId":"64018e669efe8c097857225b",
     "activityList":`Presentation,
Any 2 set,
All 3 sets,
Exploratory Activity`											     
 },
   {    
    "subActivityId":"64018e789efe8c097857225f",
     "activityList":`Presentation,
Exploratory fruits,`											     
 },
   {    
    "subActivityId":"64018ea29efe8c0978572263",
     "activityList":`Presentation,
Exploratory,
Names of content`											     
 },
   {    
    "subActivityId":"64018eb69efe8c0978572267",
     "activityList":`1 shape,
2 shapes,
Exploratory`											     
 },
  {    
    "subActivityId":"64018ee29efe8c097857226b",
     "activityList":`Objects in environment,
Montessori Material,
Parts of Object,
Scenic picture,
Classified Pictures,
Planned Conversation`											     
 },
  {    
    "subActivityId":"64018ef89efe8c097857226f",
     "activityList":`Noun,
Article,
Adjective,
Conjunction,
Preposition,
Verb,
Adverb`											     
 },
  {    
    "subActivityId":"64018f0b9efe8c0978572273",
     "activityList":`With Object,
Prel. Without Objects,
Sand paper Letter,
Listening to first sound,
Listening to last sound,
First and last sound,
SPL activity`											     
 },
  {    
    "subActivityId":"64018f2d9efe8c0978572277",
     "activityList":`Oral,
Vowels-1,
Vowels-2,
Vowels- 3,
j,
Phonograms,
sh,
ch,
th,
ng,
oo as in book,
ee as in sheep,
Open sounds,
a,
i,
o,
u_1,
u_2,
Others,
oo as in pool,
qu,
le,
Double terminal consonants,
C as in k,
Homograms,
Vowel,
Consonant,
Homophone,
Vowel,
Consonant`											     
 },
  {    
    "subActivityId":"64018f569efe8c097857227b",
     "activityList":`Letters,
Words,
Print letters,
Capital lettters,
Punctuation`											     
 },
  {    
    "subActivityId":"64018f719efe8c097857227f",
     "activityList":`Obj. box 1,
Obj. box 2,
Matching cards-picture,
Sight words,
Box-1,
Box-2,
Box-3,
Box-4,
Box-5,
Environment Cards,
Nomen. Cards,
Definition cards`											     
 },
  {    
    "subActivityId":"64018f8c9efe8c0978572283",
     "activityList":`Article,
Noun,
Adjective,
Noun-Adjective Ex.1,
Noun-Adjective Ex.2,
Verb,
Verb-Adverb Ex.1,
Verb-Adverb Ex.2,
Conjunction,
Prepostion`											     
 },
  {    
    "subActivityId":"64018fa39efe8c0978572287",
     "activityList":`Rhyming words,
gender,
antonyms,
synonyms,
homonyms,
Homophone,
Compound words`											     
 },
  {    
    "subActivityId":"64018fbc9efe8c097857228b",
     "activityList":`Names,
Sequence`											     
 },
  {    
    "subActivityId":"640190349efe8c097857228f",
     "activityList":`Number Rods,
Ask to bring rod,
Family I,
Family II,
Family III,
Sand Paper Fig,
Exercise ,
Number rods and Cards,
Exercises,
Opertions with rods,
Spindle Boxes,
Zero activity,
Chit game,
Cards and counters,
Even and odd`											     
 },
  {    
    "subActivityId":"640190689efe8c0978572293",
     "activityList":`Bead Material-Name lesson,
Arrangment,
Formation of Quantity,
Card Material-Name lesson,
Arrangment,
Formation of Qn,
Beads and cards,
Give beads ask cards,
Give cards ask beads,
Give qn ask beads and cards`											     
 },
  {    
    "subActivityId":"640190899efe8c0978572297",
     "activityList":`Change game,
Arithmetic Operation,
Addition,
Subtraction,
Multiplication,
Division`											     
 },
  {    
    "subActivityId":"640190a29efe8c097857229b",
     "activityList":`10-19 beads,
Seguin Board-1,
Beads and board,
Groups of tens- beads,
Board,
Beads and board,
11-99 beads,
Board,
11-99-beads and board,
Short bead chain,
Short bead chain with arrow,
Arrow only,
Long bead chain,
Long bead chain with arrow,
Arrow only`											     
 },
  {    
    "subActivityId":"640190c29efe8c097857229f",
     "activityList":`Cards,
Coins and cards`											     
 },
  {    
    "subActivityId":"640190dd9efe8c09785722a3",
     "activityList":`Addition Strip board,
Combination of a number,
Addition table,
Addition chart 1-2-3,
Addition snake game,
Isolate 2 bars,
COE-1,
COE-2,
Additionn blank chart,
Subtraction Strip board,
Combination,
Tables,
Subtion snake game,
COE-1,
COE-2,
Multiplication colour Bead,
commutative law,
With cards,
Multiplication board,
Multiplication chart 1-2,
Multipn blank chart,
Unit Div board,
Division chart,
Div blank chart,
Stamp Game- addition,
Stamp Game- subtion,
Stamp Game- multipion,
Stamp Game- division,
Div: 2hierarchies 0 middle 0 end,
Dot game,
Addn tracing paper,
Mental arithmetic,
Short bead frame-addition,
Short bead frame-subtration,
Long bead frame-multiplication`											     
 },
  {    
    "subActivityId":"640190ff9efe8c09785722a7",
     "activityList":`Name Lessons-qunty,
Name Lessons-cards,
Association of symbol and quanity,
Equivalence`											     
 },
  {    
    "subActivityId":"640191179efe8c09785722ab",
     "activityList":`Sand globe,
Continent globe,
Globe to map,
Continents NL,
Oceans NL,
India state Map,
States NL-southern,
Central,
Northern,
Western,
Eastern,
Land forms,
Land-Island,
Isthmus-Strait,
Gulf-Pennisula,
Bay-Cape,
Archipelago-Sys.of Lakes,
Solar system,
Types of soils,
Water cycle`											     
 },
//   {    
//     "subActivityId":"",
//      "activityList":`Timeline,
// Family tree`											     
//  },
//   {    
//     "subActivityId":"",
//      "activityList":`Cabinet,
// Names of lamina,
// Experiments,
// Parts of a plant,
// Parts of a leaf,
// Life cycle of plant`											     
//  },
//   {    
//     "subActivityId":"",
//      "activityList":`Vertebrates-Invertebrates,
// Life cycles,
// Parts of a animal`											     
//  }
 
]
module.exports = { replaceStr }