const replaceStr  =[
    
{
    "superactivityname":"Sensorial Activities",
    "activityes":"Cylinder Blocks",
    "subactivitys":"Parent presentation"
},
{"superactivityname":"Sensorial Activities","activityes":"Cylinder Blocks","subactivitys":"Reverse Pairing at random"},
{"superactivityname":"Sensorial Activities","activityes":"Cylinder Blocks","subactivitys":"Reverse Pairing in succession"},
{"superactivityname":"Sensorial Activities","activityes":"Cylinder Blocks","subactivitys":"Grading with block"},
{"superactivityname":"Sensorial Activities","activityes":"Cylinder Blocks","subactivitys":"Grading without block"},
{"superactivityname":"Sensorial Activities","activityes":"Cylinder Blocks","subactivitys":"Memory Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Cylinder Blocks","subactivitys":"Memory Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Cylinder Blocks","subactivitys":"2 at a time"},
{"superactivityname":"Sensorial Activities","activityes":"Cylinder Blocks","subactivitys":"3 at a time"},
{"superactivityname":"Sensorial Activities","activityes":"Cylinder Blocks","subactivitys":"4 at a time"},
{"superactivityname":"Sensorial Activities","activityes":"Pink Tower","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Pink Tower","subactivitys":"Memory Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Pink Tower","subactivitys":"Place Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Pink Tower","subactivitys":"Place Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Pink Tower","subactivitys":"Group Activity"},
{"superactivityname":"Sensorial Activities","activityes":"Brown Stairs","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Brown Stairs","subactivitys":"Memory Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Brown Stairs","subactivitys":"Place Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Brown Stairs","subactivitys":"Place Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Long Rods","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Long Rods","subactivitys":"Memory Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Long Rods","subactivitys":"Place Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Long Rods","subactivitys":"Place Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Long Rods","subactivitys":"Longest and next (a,b,c)"},
{"superactivityname":"Sensorial Activities","activityes":"Long Rods","subactivitys":"Longest and any (a,b,c)"},
{"superactivityname":"Sensorial Activities","activityes":"Long Rods","subactivitys":"Any 2 rods (a,b,c)"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Tablets","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Tablets","subactivitys":"Box II"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Tablets","subactivitys":"Memory Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Tablets","subactivitys":"Memory Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Tablets","subactivitys":"Grading Box III"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Tablets","subactivitys":"Place Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Tablets","subactivitys":"Place Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Tablets","subactivitys":"Exploratory"},
{"superactivityname":"Sensorial Activities","activityes":"Tactile Material","subactivitys":"Touch Board I"},
{"superactivityname":"Sensorial Activities","activityes":"Tactile Material","subactivitys":"Touch Board II"},
{"superactivityname":"Sensorial Activities","activityes":"Tactile Material","subactivitys":"Fabrics"},
{"superactivityname":"Sensorial Activities","activityes":"Tactile Material","subactivitys":"Touch Tablets pairing"},
{"superactivityname":"Sensorial Activities","activityes":"Tactile Material","subactivitys":"Grading method I"},
{"superactivityname":"Sensorial Activities","activityes":"Tactile Material","subactivitys":"Grading method II"},
{"superactivityname":"Sensorial Activities","activityes":"Tactile Material","subactivitys":"Exploratory"},
{"superactivityname":"Sensorial Activities","activityes":"Noise Boxes","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Noise Boxes","subactivitys":"Memory Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Noise Boxes","subactivitys":"Memory Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Noise Boxes","subactivitys":"Grading method I"},
{"superactivityname":"Sensorial Activities","activityes":"Noise Boxes","subactivitys":"Grading method II"},
{"superactivityname":"Sensorial Activities","activityes":"Noise Boxes","subactivitys":"Place Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Noise Boxes","subactivitys":"Place Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Noise Boxes","subactivitys":"Exploratory"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cabinet","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cabinet","subactivitys":"Multiple drawers at a time"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cabinet","subactivitys":"Reverse Pairing at random"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cabinet","subactivitys":"Memory Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cabinet","subactivitys":"Memory Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cabinet","subactivitys":"Grading"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cabinet","subactivitys":"Place Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cabinet","subactivitys":"Place Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cabinet","subactivitys":"Memory Exercise 2-Grading"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cards","subactivitys":"Pairing inset to cards"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cards","subactivitys":"Pairing Two or three sets cards"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cards","subactivitys":"Finding insets for card"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cards","subactivitys":"Memory Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cards","subactivitys":"Memory Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cards","subactivitys":"Pairing cards only"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cards","subactivitys":"Grading"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cards","subactivitys":"Grading- Memory Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cards","subactivitys":"Group Activity"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Cards","subactivitys":"Exploratory"},
{"superactivityname":"Sensorial Activities","activityes":"Super Imposed Figure","subactivitys":"Parent Activity"},
{"superactivityname":"Sensorial Activities","activityes":"Binomial Cube","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Binomial Cube","subactivitys":"Building outside box"},
{"superactivityname":"Sensorial Activities","activityes":"Binomial Cube","subactivitys":"Sorting"},
{"superactivityname":"Sensorial Activities","activityes":"Binomial Cube","subactivitys":"Superimposing"},
{"superactivityname":"Sensorial Activities","activityes":"Trinomial Cube","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Trinomial Cube","subactivitys":"Building outside box"},
{"superactivityname":"Sensorial Activities","activityes":"Trinomial Cube","subactivitys":"Sorting"},
{"superactivityname":"Sensorial Activities","activityes":"Trinomial Cube","subactivitys":"Superimposing"},
{"superactivityname":"Sensorial Activities","activityes":"Decanomial Square","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Decanomial Square","subactivitys":"Shrinking Square"},
{"superactivityname":"Sensorial Activities","activityes":"Decanomial Square","subactivitys":"Forming squares with 1 colour"},
{"superactivityname":"Sensorial Activities","activityes":"Decanomial Square","subactivitys":"Binomial Square"},
{"superactivityname":"Sensorial Activities","activityes":"Constructive Triangles","subactivitys":"Parent Presentation-rectangular Box"},
{"superactivityname":"Sensorial Activities","activityes":"Constructive Triangles","subactivitys":"Triangular Box"},
{"superactivityname":"Sensorial Activities","activityes":"Constructive Triangles","subactivitys":"Small Hexagonal Box"},
{"superactivityname":"Sensorial Activities","activityes":"Constructive Triangles","subactivitys":"Large Hexagonal Box"},
{"superactivityname":"Sensorial Activities","activityes":"Constructive Triangles","subactivitys":"Blue Triangles forming shape"},
{"superactivityname":"Sensorial Activities","activityes":"Constructive Triangles","subactivitys":"Blue Triangle moving exercise"},
{"superactivityname":"Sensorial Activities","activityes":"Constructive Triangles","subactivitys":"Blue Triangle inverting exercise"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Solids","subactivitys":"Parent presentation-Finding solid with same phase"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Solids","subactivitys":"Finding all solids with a phase"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Solids","subactivitys":"Finding solids matching all phases"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Solids","subactivitys":"Exploratory Activities"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Solids and cards","subactivitys":"Finding solid to match the card"},
{"superactivityname":"Sensorial Activities","activityes":"Geometric Solids and cards","subactivitys":"Finding all cards to match solid"},
{"superactivityname":"Sensorial Activities","activityes":"Stereognostic exerise Solids","subactivitys":"Identifying solid"},
{"superactivityname":"Sensorial Activities","activityes":"Stereognostic exerise Solids","subactivitys":"Finding solid"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Presentation bag"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Bag 2"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Bag 3"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Bag 4"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Bag 5"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Bag 6"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Bag 7"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Bag 8"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Coin box pairing"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Coin box stereo ex.1"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Coin box stereo ex.2"},
{"superactivityname":"Sensorial Activities","activityes":"Steregnostic bags","subactivitys":"Mystery bag"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Cylinder","subactivitys":"Parent activity-Grading"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Cylinder","subactivitys":"Place Exercise 1"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Cylinder","subactivitys":"Place Exercise 2"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Cylinder","subactivitys":"Vertical building one colour"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Cylinder","subactivitys":"Vertical building two colours"},
{"superactivityname":"Sensorial Activities","activityes":"Colour Cylinder","subactivitys":"Partial Pairing"},
{"superactivityname":"Sensorial Activities","activityes":"Baric Tablets","subactivitys":"Parent presentation-Pairing"},
{"superactivityname":"Sensorial Activities","activityes":"Baric Tablets","subactivitys":"Sorting"},
{"superactivityname":"Sensorial Activities","activityes":"Baric Tablets","subactivitys":"Grading baric box"},
{"superactivityname":"Sensorial Activities","activityes":"Baric Tablets","subactivitys":"Exploratory Activities"},
{"superactivityname":"Sensorial Activities","activityes":"Olfactory  Activity","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Olfactory  Activity","subactivitys":"Exploratory Activities"},
{"superactivityname":"Sensorial Activities","activityes":"Gustatory Activity","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Gustatory Activity","subactivitys":"Exploratory Activities"},
{"superactivityname":"Sensorial Activities","activityes":"Gustatory Activity","subactivitys":"Grading"},
{"superactivityname":"Sensorial Activities","activityes":"Gustatory Activity","subactivitys":"Taste Analysis"},
{"superactivityname":"Sensorial Activities","activityes":"Thermic Slabs","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Thermic Slabs","subactivitys":"Exercise-1 set out"},
{"superactivityname":"Sensorial Activities","activityes":"Thermic Slabs","subactivitys":"Exercise-heat retaining capacity"},
{"superactivityname":"Sensorial Activities","activityes":"Drawing Insets","subactivitys":"Parent presentation"},
{"superactivityname":"Sensorial Activities","activityes":"Drawing Insets","subactivitys":"Same inset different orientation"},
{"superactivityname":"Sensorial Activities","activityes":"Drawing Insets","subactivitys":"Different insets combinations"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods","subactivitys":"Parent Presentaion"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods","subactivitys":"Asking for a rod"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods","subactivitys":"Asking for a rod-not arranged"},
{"superactivityname":"Arithmetic Activities","activityes":"Sand paper figures","subactivitys":"Special name lesson"},
{"superactivityname":"Arithmetic Activities","activityes":"Sand paper figures","subactivitys":"Give me a number"},
{"superactivityname":"Arithmetic Activities","activityes":"Sand paper figures","subactivitys":"Distribute the numbers"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods and Cards","subactivitys":"Parent Presentaion"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods and Cards","subactivitys":"Shuffle cards"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods and Cards","subactivitys":"Rods not arranged"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods and Cards","subactivitys":"Shuffle cards+ Rods not arranged"},
{"superactivityname":"Arithmetic Activities","activityes":"Spindle Boxes","subactivitys":"0 to 4"},
{"superactivityname":"Arithmetic Activities","activityes":"Spindle Boxes","subactivitys":"5 to 9"},
{"superactivityname":"Arithmetic Activities","activityes":"Zero Activity","subactivitys":"Group"},
{"superactivityname":"Arithmetic Activities","activityes":"Chit Game","subactivitys":"Group"},
{"superactivityname":"Arithmetic Activities","activityes":"Cards and Counters","subactivitys":"Presentation"},
{"superactivityname":"Arithmetic Activities","activityes":"Cards and Counters","subactivitys":"Odd and Even"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods-special ex.","subactivitys":"10 next longest (a,b,c)"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods-special ex.","subactivitys":"10 and any (a,b,c)"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods-special ex.","subactivitys":"Any 2 rods (a,b,c)"},
{"superactivityname":"Arithmetic Activities","activityes":"Number Rods-special ex.","subactivitys":"Arithmetic operations"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system static  beads","subactivitys":"Name Lesson"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system static  beads","subactivitys":"Arrangment of bead material"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system static  beads","subactivitys":"Formation of quantity"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system cards","subactivitys":"Name Lesson"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system cards","subactivitys":"Arrangment of bead material"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system cards","subactivitys":"Formation of quantity"},
{"superactivityname":"Arithmetic Activities","activityes":"Static part Bead and Card","subactivitys":"Give beads ask cards"},
{"superactivityname":"Arithmetic Activities","activityes":"Static part Bead and Card","subactivitys":"Give cards ask beads"},
{"superactivityname":"Arithmetic Activities","activityes":"Static part Bead and Card","subactivitys":"Give quantity ask beads and cards"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system dynamic","subactivitys":"Change game"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system dynamic","subactivitys":"Addition without change"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system dynamic","subactivitys":"Addition with change"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system dynamic","subactivitys":"Subtraction without change"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system dynamic","subactivitys":"Subtraction with change"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system dynamic","subactivitys":"Multiplication without change"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system dynamic","subactivitys":"Multiplication with change"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system dynamic","subactivitys":"Dividion without change"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system dynamic","subactivitys":"Division with change"},
{"superactivityname":"Arithmetic Activities","activityes":"Decimal system dynamic","subactivitys":"Division with change and remainder"},
{"superactivityname":"Arithmetic Activities","activityes":"Traditional names-One ten and units","subactivitys":"Beads"},
{"superactivityname":"Arithmetic Activities","activityes":"Traditional names-One ten and units","subactivitys":"Seguin board I"},
{"superactivityname":"Arithmetic Activities","activityes":"Traditional names-One ten and units","subactivitys":"Beads and seguin board I"},
{"superactivityname":"Arithmetic Activities","activityes":"Traditional names-One ten and units","subactivitys":"Colour beads and cards"},
{"superactivityname":"Arithmetic Activities","activityes":"Traditional names-Groups of tens","subactivitys":"Beads"},
{"superactivityname":"Arithmetic Activities","activityes":"Traditional names-Groups of tens","subactivitys":"Cards"},
{"superactivityname":"Arithmetic Activities","activityes":"Traditional names-Groups of tens","subactivitys":"Beads and cards"},
{"superactivityname":"Arithmetic Activities","activityes":"Traditional names-Groups of tens and units","subactivitys":"Beads"},
{"superactivityname":"Arithmetic Activities","activityes":"Traditional names-Groups of tens and units","subactivitys":"Cards"},
{"superactivityname":"Arithmetic Activities","activityes":"Traditional names-Groups of tens and units","subactivitys":"Beads and cards"},
{"superactivityname":"Arithmetic Activities","activityes":"Consolidation activities","subactivitys":"Chart-1,100 written"},
{"superactivityname":"Arithmetic Activities","activityes":"Consolidation activities","subactivitys":"Chart-first row  and column filled"},
{"superactivityname":"Arithmetic Activities","activityes":"Consolidation activities","subactivitys":"Chart with tiles/writing picking numbers randomly"},
{"superactivityname":"Arithmetic Activities","activityes":"Consolidation activities","subactivitys":"Seguin board II"},
{"superactivityname":"Arithmetic Activities","activityes":"Consolidation activities","subactivitys":"Seguin board II and beads"},
{"superactivityname":"Arithmetic Activities","activityes":"Consolidation activities","subactivitys":"Seguin board II and colour beads"},
{"superactivityname":"Arithmetic Activities","activityes":"Short bead chain","subactivitys":"Chain activity"},
{"superactivityname":"Arithmetic Activities","activityes":"Short bead chain","subactivitys":"Chains with arrows"},
{"superactivityname":"Arithmetic Activities","activityes":"Short bead chain","subactivitys":"Chains with arrows -square of a number"},
{"superactivityname":"Arithmetic Activities","activityes":"Short bead chain","subactivitys":"Chains with arrows- choosing arrows"},
{"superactivityname":"Arithmetic Activities","activityes":"Short bead chain","subactivitys":"Arrows only"},
{"superactivityname":"Arithmetic Activities","activityes":"Long bead chain","subactivitys":"Chain activity"},
{"superactivityname":"Arithmetic Activities","activityes":"Long bead chain","subactivitys":"Chains with arrows"},
{"superactivityname":"Arithmetic Activities","activityes":"Long bead chain","subactivitys":"Chains with arrows -cube of a number"},
{"superactivityname":"Arithmetic Activities","activityes":"Long bead chain","subactivitys":"Arrows only"},
{"superactivityname":"Arithmetic Activities","activityes":"Construction","subactivitys":"Construct a line"},
{"superactivityname":"Arithmetic Activities","activityes":"Construction","subactivitys":"Angle using protractor"},
{"superactivityname":"Arithmetic Activities","activityes":"Construction","subactivitys":"Circle using compass"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Addition","subactivitys":"Strip board"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Addition","subactivitys":"Strip board 10 combinations"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Addition","subactivitys":"Strip board-table"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Addition","subactivitys":"Addition full chart"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Addition","subactivitys":"Addition half chart 1"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Addition","subactivitys":"Addition half chart 2"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Addition","subactivitys":"Addition blank chart"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Addition","subactivitys":"Snake game"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Addition","subactivitys":"Snake game COE  10 combinations"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Addition","subactivitys":"Snake game COE  multiple beads together"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Subtraction","subactivitys":"Strip board"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Subtraction","subactivitys":"Strip board 10 combinations"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Subtraction","subactivitys":"Strip board-table"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Subtraction","subactivitys":"Subtraction full chart"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Subtraction","subactivitys":"Subtraction blank chart"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Subtraction","subactivitys":"Snake game"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Subtraction","subactivitys":"Snake game COE  tally colour and transparent"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Subtraction","subactivitys":"Snake game COE- separate snakes and tally"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Multiplication","subactivitys":"Coloured bead bars CBB"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Multiplication","subactivitys":"CBB one card and one colour bar"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Multiplication","subactivitys":"CBB one card and two colour bars"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Multiplication","subactivitys":"CBB Two cards and one colour bar"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Multiplication","subactivitys":"CBB Two cards and two colour bar"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Multiplication","subactivitys":"Multiplication board"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Multiplication","subactivitys":"Multiplication full chart"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Multiplication","subactivitys":"Multiplication half chart 1"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises-Multiplication","subactivitys":"Multiplication blank chart"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises Division","subactivitys":"Unit division board"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises Division","subactivitys":"Division full chart"},
{"superactivityname":"Arithmetic Activities","activityes":"Parallel Exercises Division","subactivitys":"Division blank chart"},
{"superactivityname":"Arithmetic Activities","activityes":"Stamp Game","subactivitys":"Addition"},
{"superactivityname":"Arithmetic Activities","activityes":"Stamp Game","subactivitys":"Subtraction without change"},
{"superactivityname":"Arithmetic Activities","activityes":"Stamp Game","subactivitys":"Subtraction with change"},
{"superactivityname":"Arithmetic Activities","activityes":"Stamp Game","subactivitys":"Multiplication"},
{"superactivityname":"Arithmetic Activities","activityes":"Stamp Game","subactivitys":"Division in units place"},
{"superactivityname":"Arithmetic Activities","activityes":"Stamp Game","subactivitys":"Division by two heirarchies"},
{"superactivityname":"Arithmetic Activities","activityes":"Stamp Game","subactivitys":"Division with 3 heirarchies and 0 in tens place"},
{"superactivityname":"Arithmetic Activities","activityes":"Stamp Game","subactivitys":"Division with 0 in units place"},
{"superactivityname":"Arithmetic Activities","activityes":"Short bead frame","subactivitys":"Addition w/o change"},
{"superactivityname":"Arithmetic Activities","activityes":"Short bead frame","subactivitys":"Addition with change"},
{"superactivityname":"Arithmetic Activities","activityes":"Short bead frame","subactivitys":"Subtraction w/o change"},
{"superactivityname":"Arithmetic Activities","activityes":"Short bead frame","subactivitys":"Subtraction with change"},
{"superactivityname":"Arithmetic Activities","activityes":"Long bead frame","subactivitys":"Multiplication method I"},
{"superactivityname":"Arithmetic Activities","activityes":"Long bead frame","subactivitys":"Multiplication method II"},
{"superactivityname":"Arithmetic Activities","activityes":"Towards Abstraction","subactivitys":"Dot game addition"},
{"superactivityname":"Arithmetic Activities","activityes":"Towards Abstraction","subactivitys":"Tracing paper addition"},
{"superactivityname":"Arithmetic Activities","activityes":"Mental arithmetic","subactivitys":"Addition w/o carry over"},
{"superactivityname":"Arithmetic Activities","activityes":"Mental arithmetic","subactivitys":"Addition with carry over"},
{"superactivityname":"Arithmetic Activities","activityes":"Mental arithmetic","subactivitys":"Word problems"},
{"superactivityname":"Arithmetic Activities","activityes":"Mental arithmetic","subactivitys":"Multiplication table"},
{"superactivityname":"Arithmetic Activities","activityes":"Mental arithmetic","subactivitys":"Subtraction  w/o carry over"},
{"superactivityname":"Arithmetic Activities","activityes":"Mental arithmetic","subactivitys":"Subtraction with carry over"},
{"superactivityname":"Arithmetic Activities","activityes":"Fractions","subactivitys":"Name Lesson"},
{"superactivityname":"Arithmetic Activities","activityes":"Fractions","subactivitys":"Symbols"},
{"superactivityname":"Arithmetic Activities","activityes":"Fractions","subactivitys":"Equivalence"},
{"superactivityname":"Arithmetic Activities","activityes":"Fractions","subactivitys":"Operations"},
{"superactivityname":"Arithmetic Activities","activityes":"Higher Arithmetic","subactivitys":"Long Multiplication"},
{"superactivityname":"Arithmetic Activities","activityes":"Higher Arithmetic","subactivitys":"Long Division"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Sand Globe"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Continent globe"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Globe-Map"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"World Map"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Ocean names"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Asia Map"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"India Map"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Neighbouring countries"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Landforms-Lake/Island"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Landforms-Isthmus/strait"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Landforms-Gulf/Peninsula"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Landforms-Cape/Bay"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Directions-Right/left"},
{"superactivityname":"Cultural Activities","activityes":"Geography","subactivitys":"Directions-NSEW"},
{"superactivityname":"Cultural Activities","activityes":"Botany","subactivitys":"Parts of  tree/plant"},
{"superactivityname":"Cultural Activities","activityes":"Botany","subactivitys":"Parts of leaf"},
{"superactivityname":"Cultural Activities","activityes":"Botany","subactivitys":"Parts of root"},
{"superactivityname":"Cultural Activities","activityes":"Botany","subactivitys":"Parts of a flower"},
{"superactivityname":"Cultural Activities","activityes":"Botany","subactivitys":"Part of fruit"},
{"superactivityname":"Cultural Activities","activityes":"Botany","subactivitys":"Life cycle of plant"},
{"superactivityname":"Cultural Activities","activityes":"Botany","subactivitys":"Botany Cabinet"},
{"superactivityname":"Cultural Activities","activityes":"Botany","subactivitys":"Leaf Lamina"},
{"superactivityname":"Cultural Activities","activityes":"Botany","subactivitys":"Types of roots"},
{"superactivityname":"Cultural Activities","activityes":"Botany","subactivitys":"Types of plants"},
{"superactivityname":"Cultural Activities","activityes":"Zoology","subactivitys":"Parts of an animal"},
{"superactivityname":"Cultural Activities","activityes":"Zoology","subactivitys":"Life cycle of animal"},
{"superactivityname":"Cultural Activities","activityes":"Zoology","subactivitys":"Animal drawing"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Roll work mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Unroll work mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Fold sitting mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Unfold sitting mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Sit on work mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Get up from work mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Sit on sitting mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Get up from sitting mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Sit on a chair"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Get up from chair"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Sit on a chair at a table"},
{"superactivityname":"Exercise of Practical Life","activityes":"Elementary movements","subactivitys":"Get up from chair at a table"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Chowki"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Chair"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Bucket"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Rolled Mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Sitting mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Oil cloth on mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Oil cloth on Chowki"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Small glass"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Medium glass"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Small Jug"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Medium Jug"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Large jug"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Lota"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Napkin"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to put down","subactivitys":"Duster"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Chowki"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Chair"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Rolled Mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Sitting mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Oil cloth"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Small glass"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Medium glass"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Small Jug"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Medium Jug"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Large jug"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Bucket"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Lota"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Napkin"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to hold and lift","subactivitys":"Duster"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Rolled Mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Oil cloth"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Chair"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Chowki"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Tray"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Bucket"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Napkin"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Duster"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Dustpan and Brush"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Broom"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Large Table"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Pair of scissors"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Knife"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Pencil"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to Carry","subactivitys":"Pen"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Fold Napkin along medials"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Unfold Napkin along medials"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Fold Napkin along diagonals"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Unfold Napkin along diagonals"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Choose a duster"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Fold a duster for display"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"unfold a duster folded for display"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Fold a duster for use"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"unfold a duster folded for use"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Roll an oil cloth on mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Unroll oil cloth on mat"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Roll oil cloth on chowki"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Unroll oil cloth on chowki"},
{"superactivityname":"Exercise of Practical Life","activityes":"How to fold/unfold","subactivitys":"Fold clothes/aprons"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Spooning"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Stone removal with spoon"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Sponging tray to bowl"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Transfer water with sponge"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Transfer water with funnel"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Pouring solids"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Pouring liquids"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Using squeezer with sponge"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Using tong with sponge"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Using tweezer small objects"},
{"superactivityname":"Exercise of Practical Life","activityes":"Transferring activities","subactivitys":"Cloth clip"},
{"superactivityname":"Exercise of Practical Life","activityes":"Kitchen activities","subactivitys":"Peanut shelling"},
{"superactivityname":"Exercise of Practical Life","activityes":"Kitchen activities","subactivitys":"Pounding"},
{"superactivityname":"Exercise of Practical Life","activityes":"Kitchen activities","subactivitys":"Peeling"},
{"superactivityname":"Exercise of Practical Life","activityes":"Kitchen activities","subactivitys":"Grating"},
{"superactivityname":"Exercise of Practical Life","activityes":"Kitchen activities","subactivitys":"Chopping"},
{"superactivityname":"Exercise of Practical Life","activityes":"Kitchen activities","subactivitys":"Chapathi making"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of environment","subactivitys":"Use a dustpan brush"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of environment","subactivitys":"How to boom"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of environment","subactivitys":"How to dust Chowki"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of environment","subactivitys":"How to polish brass"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of environment","subactivitys":"How to wash a table"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of environment","subactivitys":"How to take care of plant"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of environment","subactivitys":"Rnagoli"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of environment","subactivitys":"Cleaning glass"},
{"superactivityname":"Exercise of Practical Life","activityes":"Stitching","subactivitys":"Lacing pattern"},
{"superactivityname":"Exercise of Practical Life","activityes":"Stitching","subactivitys":"Threading a needle"},
{"superactivityname":"Exercise of Practical Life","activityes":"Stitching","subactivitys":"Making knots"},
{"superactivityname":"Exercise of Practical Life","activityes":"Stitching","subactivitys":"Winding thread/wool"},
{"superactivityname":"Exercise of Practical Life","activityes":"Stitching","subactivitys":"Stitching button"},
{"superactivityname":"Exercise of Practical Life","activityes":"Stitching","subactivitys":"Stitching hook"},
{"superactivityname":"Exercise of Practical Life","activityes":"Stitching","subactivitys":"Straight stitch"},
{"superactivityname":"Exercise of Practical Life","activityes":"Stitching","subactivitys":"Cross stitch"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Washing hands"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Washing clothes"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Fasten press button"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Unfasten press button"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Fasten hook and eye"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Unfasten hook and eye"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Fasten coat button"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Unfasten coat button"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Fasten Buckle frame"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Unfasten Buckle frame"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Tie base knot ribbon"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Untie base knot ribbon"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Tie bow"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Untie a bow"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Lace frame- tying v pattern"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Lace frame- untying v pattern"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Lace frame- tying x pattern"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Lace frame- untying x pattern"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Lace frame- tying linear pattern"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Lace frame- untying linear pattern"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Buttoning sleeve"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Shirt button"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Stringing pyjama"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Fastening safety pin"},
{"superactivityname":"Exercise of Practical Life","activityes":"Taking care of self","subactivitys":"Unfasten safety pin"},
{"superactivityname":"Exercise of Practical Life","activityes":"Weaving frame","subactivitys":"Weft- strips"},
{"superactivityname":"Exercise of Practical Life","activityes":"Weaving frame","subactivitys":"Weft- wool"},
{"superactivityname":"Exercise of Practical Life","activityes":"Weaving frame","subactivitys":"Warp and weft"},
{"superactivityname":"Exercise of Practical Life","activityes":"Self control","subactivitys":"Walking on line"},
{"superactivityname":"Exercise of Practical Life","activityes":"Self control","subactivitys":"Silence Activity"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Removing cotton seed"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Making cotton wicks"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Putting pillow case"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Making crepe paper balls"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"How to use scissors"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Cutting patterns"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Cutting design"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Push pin activity"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Braiding level 1"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Braiding level 2"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Vertical braiding"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Rubbing crayon pattern"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Flower braiding"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Rubber band activity"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Pattern-vaccum cups"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Flower decoration"},
{"superactivityname":"Exercise of Practical Life","activityes":"Additional","subactivitys":"Lighting match stick"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Puzzles"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Stringing beads"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Pairing-objects"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Pairing-object picture"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Pairing- related"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Sorting- shape"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Sorting-colour"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Screwing"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Following a pattern"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Fist transfer big"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Fist transfer small"},
{"superactivityname":"Exercise of Practical Life","activityes":"Preliminary activities","subactivitys":"Shadow matching"},
{"superactivityname":"Language Activities","activityes":"Enrichment of vocabulary","subactivitys":"Commands"},
{"superactivityname":"Language Activities","activityes":"Enrichment of vocabulary","subactivitys":"Object in environment"},
{"superactivityname":"Language Activities","activityes":"Enrichment of vocabulary","subactivitys":"Montessori Objects"},
{"superactivityname":"Language Activities","activityes":"Enrichment of vocabulary","subactivitys":"Scenic picture"},
{"superactivityname":"Language Activities","activityes":"Enrichment of vocabulary","subactivitys":"Planned Conversation"},
{"superactivityname":"Language Activities","activityes":"Preparatory activities in sound","subactivitys":"With object box"},
{"superactivityname":"Language Activities","activityes":"Preparatory activities in sound","subactivitys":"without object box"},
{"superactivityname":"Language Activities","activityes":"Sand paper letters","subactivitys":"Identify the letter"},
{"superactivityname":"Language Activities","activityes":"Sand paper letters","subactivitys":"Distribute the letters"},
{"superactivityname":"Language Activities","activityes":"Sand paper letters","subactivitys":"This or that"},
{"superactivityname":"Language Activities","activityes":"Oral Phonetic analysis","subactivitys":"First sound"},
{"superactivityname":"Language Activities","activityes":"Oral Phonetic analysis","subactivitys":"Last sound"},
{"superactivityname":"Language Activities","activityes":"Oral Phonetic analysis","subactivitys":"First and Last sound"},
{"superactivityname":"Language Activities","activityes":"Help with vowel","subactivitys":"Sorting objects"},
{"superactivityname":"Language Activities","activityes":"Help with vowel","subactivitys":"Sorting cards"},
{"superactivityname":"Language Activities","activityes":"Movable alphabets","subactivitys":"Oral"},
{"superactivityname":"Language Activities","activityes":"Movable alphabets","subactivitys":"Vowel-1"},
{"superactivityname":"Language Activities","activityes":"Movable alphabets","subactivitys":"Vowel-2"},
{"superactivityname":"Language Activities","activityes":"Movable alphabets","subactivitys":"Vowel-3"},
{"superactivityname":"Language Activities","activityes":"Movable alphabets","subactivitys":"Vowel-4"},
{"superactivityname":"Language Activities","activityes":"Movable alphabets","subactivitys":"Vowel-e"},
{"superactivityname":"Language Activities","activityes":"Movable alphabets","subactivitys":"Phonograms"},
{"superactivityname":"Language Activities","activityes":"Script","subactivitys":"print and cursive small"},
{"superactivityname":"Language Activities","activityes":"Script","subactivitys":"Cursive small and capital"},
{"superactivityname":"Language Activities","activityes":"Script","subactivitys":"Print  and cursive capital"},
{"superactivityname":"Language Activities","activityes":"Small movable alphabets","subactivitys":"Long vowel sound"},
{"superactivityname":"Language Activities","activityes":"Small movable alphabets","subactivitys":"Double terminal consonant"},
{"superactivityname":"Language Activities","activityes":"Small movable alphabets","subactivitys":"Metathesis"},
{"superactivityname":"Language Activities","activityes":"Small movable alphabets","subactivitys":"c,q, x"},
{"superactivityname":"Language Activities","activityes":"Small movable alphabets","subactivitys":"Homophones"},
{"superactivityname":"Language Activities","activityes":"Small movable alphabets","subactivitys":"Homograms"},
{"superactivityname":"Language Activities","activityes":"Help with consonants","subactivitys":"b and d"},
{"superactivityname":"Language Activities","activityes":"Help with consonants","subactivitys":"v and w"},
{"superactivityname":"Language Activities","activityes":"Emphatic consonant","subactivitys":"Group"},
{"superactivityname":"Language Activities","activityes":"Emphatic consonant","subactivitys":"Sorting card"},
{"superactivityname":"Language Activities","activityes":"Writing","subactivitys":"Patterns"},
{"superactivityname":"Language Activities","activityes":"Writing","subactivitys":"Letters small"},
{"superactivityname":"Language Activities","activityes":"Writing","subactivitys":"Letters capital"},
{"superactivityname":"Language Activities","activityes":"Writing","subactivitys":"Words"},
{"superactivityname":"Language Activities","activityes":"Writing","subactivitys":"Sentences"},
{"superactivityname":"Language Activities","activityes":"Writing","subactivitys":"Creative writing"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Pairing with objects"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Phonetic words"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Phonograms"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Long vowel sound"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Double terminal consonant"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Metathesis"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"c,q, x"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Homophones"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Homograms"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Emphatic consonants"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Starting blends"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Ending blends"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Sight words"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Sentences"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Command cards"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Comprehension"},
{"superactivityname":"Language Activities","activityes":"Reading","subactivitys":"Stories"},
{"superactivityname":"Language Activities","activityes":"Grammar oral","subactivitys":"Noun"},
{"superactivityname":"Language Activities","activityes":"Grammar oral","subactivitys":"Verb"},
{"superactivityname":"Language Activities","activityes":"Grammar oral","subactivitys":"Transitive/intransitive verb"},
{"superactivityname":"Language Activities","activityes":"Grammar oral","subactivitys":"Adjective"},
{"superactivityname":"Language Activities","activityes":"Grammar oral","subactivitys":"Adverb"},
{"superactivityname":"Language Activities","activityes":"Grammar oral","subactivitys":"Preposition"},
{"superactivityname":"Language Activities","activityes":"Grammar oral","subactivitys":"Conjuction"},
{"superactivityname":"Language Activities","activityes":"Grammar oral","subactivitys":"Subject"},
{"superactivityname":"Language Activities","activityes":"Grammar oral","subactivitys":"Object"},
{"superactivityname":"Language Activities","activityes":"Grammar oral","subactivitys":"Article"},
{"superactivityname":"Language Activities","activityes":"Grammar written","subactivitys":"Noun"},
{"superactivityname":"Language Activities","activityes":"Grammar written","subactivitys":"Verb"},
{"superactivityname":"Language Activities","activityes":"Grammar written","subactivitys":"Adjective"},
{"superactivityname":"Language Activities","activityes":"Grammar written","subactivitys":"Adverb"},
{"superactivityname":"Language Activities","activityes":"Grammar written","subactivitys":"Preposition"},
{"superactivityname":"Language Activities","activityes":"Grammar written","subactivitys":"Conjuction"},
{"superactivityname":"Language Activities","activityes":"Grammar written","subactivitys":"Article"},
{"superactivityname":"Language Activities","activityes":"Analysis","subactivitys":"Sentence analysis"},
{"superactivityname":"Language Activities","activityes":"Analysis","subactivitys":"Transposition"},
{"superactivityname":"Language Activities","activityes":"Analysis","subactivitys":"One verb- many adverbs"},
{"superactivityname":"Language Activities","activityes":"Analysis","subactivitys":"One adverb-many verbs"},
{"superactivityname":"Language Activities","activityes":"Analysis","subactivitys":"One noun-many adjectives"},
{"superactivityname":"Language Activities","activityes":"Analysis","subactivitys":"One adj-many nouns"},
{"superactivityname":"Language Activities","activityes":"Correct expression","subactivitys":"Rhyming words"},
{"superactivityname":"Language Activities","activityes":"Correct expression","subactivitys":"Synonyms"},
{"superactivityname":"Language Activities","activityes":"Correct expression","subactivitys":"Antonyms"},
{"superactivityname":"Language Activities","activityes":"Correct expression","subactivitys":"Homonyms"},
{"superactivityname":"Language Activities","activityes":"Correct expression","subactivitys":"Animal and young"},
{"superactivityname":"Language Activities","activityes":"Correct expression","subactivitys":"Animal and home"},
{"superactivityname":"Language Activities","activityes":"Correct expression","subactivitys":"Animal gender names"},
{"superactivityname":"Language Activities","activityes":"Correct expression","subactivitys":"Singular plural"},
{"superactivityname":"Language Activities","activityes":"Communication","subactivitys":"Describing an object"},
{"superactivityname":"Language Activities","activityes":"Communication","subactivitys":"Narrate an incident"},
{"superactivityname":"Language Activities","activityes":"Communication","subactivitys":"Narrate a story"},
{"superactivityname":"Language Activities","activityes":"Spellings","subactivitys":"Days of a week"},
{"superactivityname":"Language Activities","activityes":"Spellings","subactivitys":"Number names"},
{"superactivityname":"Language Activities","activityes":"Spellings","subactivitys":"Colours"},
{"superactivityname":"Language Activities","activityes":"Spellings","subactivitys":"Fruits, vegetables"},
{"superactivityname":"Language Activities","activityes":"Spellings","subactivitys":"Own name, place"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Enrichment of vocabulary"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Preparatory sound activities"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Sand paper letters"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Sand paper letter exercises"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Oral phonetic analysis"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Grammar"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Varnamala ki petti"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Matra ki petti"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Writing letters"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Writing words"},
{"superactivityname":"Language Activities","activityes":"Hindi activities","subactivitys":"Writing words with matras"}
]
   

   module.exports = { replaceStr }